version: '3'
services:
  postgresDb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: beeUser       
      POSTGRES_PASSWORD: {password here}
      POSTGRES_DB: beeTrack           
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - /var/lib/postrgesql/data:/var/lib/postgresql/data
  app:
    image: mthomas564/beetrack:39cba230b470a9bfeaed7658bcdd326df3f1b69c
    restart: always
    environment:
      - POSTGRES_HOST=postgresDb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=beeUser
      - POSTGRES_PASSWORD={password here}
      - POSTGRES_DB=beeTrack
    ports:
      - '3000:3000'
    depends_on:
      - postgresDb